version: '3'
services:
  postgres:
    build: ./environment/postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  localstack:
    build: ./environment/localstack    
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
